version: '3.1'

services:
  app:
    container_name: credit-services
    image: credit-services
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
      
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=postgres_db